spring:
  application:
    name: edu-manage-demo
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:edu_manage.db
    username:
    password:

server:
  port: 15561

logging:
  config: classpath:logback.xml
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: '*'